#!/bin/bash
# VibeStack Welcome Menu

# Check if we should skip the menu
if [ "$VIBESTACK_NO_MENU" = "1" ]; then
    exit 0
fi

# Check if this is an interactive terminal
if [ -t 0 ] && [ -t 1 ]; then
    # Run the interactive menu
    cd /home/vibe/vibestack-menu && node menu-new.js
else
    # Non-interactive terminal, don't show any messages
    exit 0
fi