version: '3.8'

services:
  novnc-container:
    build: .
    ports:
      - "${NOVNC_PORT:-6080}:6080"
      - "2222:22"  # SSH port mapped to avoid conflicts
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - NOVNC_PORT=${NOVNC_PORT:-6080}
      - VNC_PORT=${VNC_PORT:-5900}
      - RESOLUTION=${RESOLUTION:-1280x720}
      - VNC_PASSWORD=${VNC_PASSWORD:-}
    volumes:
      - ./mnt:/home/vnc/mnt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/vnc.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s