#!/bin/sh
# Fluxbox startup script
# Applications to start with fluxbox - MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN '&' AT THE END

# Load X resources configuration
xrdb -merge ~/.Xresources

# Start xterm in fullscreen mode
# xterm -name xterm-fullscreen -title "Terminal" &

# Wait a moment for xterm to start
sleep 1

# Start fluxbox window manager (must be last)
exec fluxbox