// Vibestack Configuration
// This file is auto-generated by vibestack-configure-extension
// If not configured, the extension will use auto-detection

if (typeof window.VIBESTACK_CONFIG === 'undefined') {
    window.VIBESTACK_CONFIG = {
        baseUrl: '',
        apiUrl: '',
        configured: false
    };
}
