name: Publish Docker image

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    tags:
      - 'v*'          # Auto-run on version tags like v1.0.0
    branches:
      - main          # Auto-run on push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to publish to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/check-the-vibe/vibestack
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}
            # Add 'latest' tag if we're on main
          flavor: |
            latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}